### ISSUE TITLE
Rune doesn't work on Ubuntu 18.XX

### ISSUE THREAD

**Issue by kthakore** [hotg-ai/rune#108]
I get this error `lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./rune)`

When using the nightly rune prebuilt executable

**Comment by kthakore** [comment]
@Michael-F-Bryan  see https://colab.research.google.com/drive/18Q0xlUPRD96ieRbWdUjLkcnKyO_FyR7Z#scrollTo=qbfPtQUwZWqv

**Comment by Michael-F-Bryan** [comment]
It looks like the `rune` executable is wanting to link to the same (or newer) version of `glibc` that it was compiled with. We have two options here:

1. update our GitHub Actions to use an older version of Linux (e.g. Ubuntu 18.04) instead of `ubuntu-latest` (20.04), or
2. say that people need to be using a relatively recent version of Linux/libc.

As a point of interest, Ubuntu 20.04 is the current Ubuntu LTS.
