### ISSUE TITLE
Some runes return "<Missing>" result in mobile app when called multiple times

### ISSUE THREAD

**Issue by Ge-te** [hotg-ai/rune#130]
Debouncer causes mobile app to receive  "\<MISSING\>"  output.
App now retries until model output is received.
Happens in gesture and person detection.

**Comment by Mi1ind** [comment]
[UNKNOWN_LABEL](https://github.com/hotg-ai/rune/blob/f0eb54d0e35d22094b63f4926d916c1ee8da4e52/proc_blocks/person_detection_agg/src/lib.rs#L24) is being called in the proc_block.

It's probably happening because of [throttling](https://github.com/hotg-ai/rune/blob/f0eb54d0e35d22094b63f4926d916c1ee8da4e52/proc_blocks/person_detection_agg/src/lib.rs#L98-L104).
